### ISSUE TITLE
EPIC: Build a Back-End for a Full-Stack web application

### ISSUE THREAD

**Issue by sbojorge** [sbojorge/DRF-urbantrip#1]
As a **developper** I want to **build a back-end API for a content sharing platform for city trip lovers** so that **users can store and manipulate data**.

## Acceptance criteria
  * Acceptance criteria 1: Use Django and Django Rest Framework for building the API.
  * Acceptance criteria 2: Besides the user and profile models, the database structure must have models to create posts, comments, like/unlike content, vote on polls, follow/unfollow users, send notifications to users when another user has commented/liked one of their posts or someone has viewed their profile.
  * Acceptance criteria 3: Records in the API must have the CRUD functionality.
  * Acceptance criteria 4: The final version of the API must be deployed to Heroku and match the development version.
  
 ## Tasks
 - [ ] Task 1: Install Django, create a project and a superuser to access the admin panel.
 - [ ] Taks 2: Install Django Rest Framework, create the models, their views, urls, serializers and their CRUD functionality.
 - [ ] Task 3: Tidy up things and deploy on Heroku.
