### ISSUE TITLE
CRUD: Create a profile instance

### ISSUE THREAD

**Issue by sbojorge** [sbojorge/DRF-urbantrip#9]
Epic #7 
As a **developer** I want to **create a profile** so that **the CREATE functionality is enabled**.

## Acceptance criteria
  * Acceptance criteria: A profile must be created every time a user instance is saved.
 
## Tasks
 - [ ] Task 1: Import post_save and receiver at the top of the Profile model.
 - [ ] Taks 2: Create the receiver function. 
 - [ ] Task 3: Connect the receiver function with the dispatcher using decorators.
